//! PincerFile, PincerUri, PincerServer, PincerServerItem
//!
//! ### Architectural Overview
//! - **What it does**: Defines data transfer models for RPC query and inspection methods (`pin.getFiles`, `pin.getUris`, `pin.getServers`).
//! - **How it does**: Formats individual file indexes, paths, selection states, URI usage states, and per-server download rate metrics into Serde-serializable structs.
//! - **Where it comes from**: Generated by `rpc::handlers::IntrospectionHandlers`.
//! - **Where it leads to**: Returned to client applications inspecting internal download components.

use serde::{Deserialize, Serialize};

/// Detailed file status entry returned by `pin.getFiles`.
#[derive(Debug, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct PincerFile {
    /// 1-based index string of the file within the task.
    pub index: String,
    /// Absolute filesystem path.
    pub path: String,
    /// Total file length in bytes.
    pub length: String,
    /// Completed byte count.
    pub completed_length: String,
    /// Indicates whether the file is selected for download ("true" / "false").
    pub selected: String,
    /// List of URIs currently being utilized for this file.
    pub uris: Vec<PincerUri>,
}

/// URI status entry returned in file and task inspection responses.
#[derive(Debug, Serialize, Deserialize)]
pub struct PincerUri {
    /// Remote resource URI string.
    pub uri: String,
    /// Connection state of this URI (e.g. "used", "waiting").
    pub status: String,
}

/// Server connection group descriptor returned by `pin.getServers`.
#[derive(Debug, Serialize, Deserialize)]
pub struct PincerServer {
    /// 1-based index string of the file being served.
    pub index: String,
    /// List of active server connection endpoints.
    pub servers: Vec<PincerServerItem>,
}

/// Individual server connection metric entry.
#[derive(Debug, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct PincerServerItem {
    /// Initial requested URI.
    pub uri: String,
    /// Effective redirected URI.
    pub current_uri: String,
    /// Instantaneous download bandwidth from this endpoint (bytes/sec).
    pub download_speed: String,
}
