//! ResolveResponse
//!
//! ### Architectural Overview
//! - **What it does**: Defines the data transfer model returned by URL and torrent inspection methods (`pin.resolveUrl`, `pin.resolveTorrent`).
//! - **How it does**: Serializes resolved URLs, inferred file names, byte lengths, MIME file types, resumability flags, and selective torrent file lists.
//! - **Where it comes from**: Generated by `resolver::UniversalResolver` and `resolver::TorrentResolver`.
//! - **Where it leads to**: Returned to client applications to pre-populate file names and sizes before downloading starts.

use super::torrent::TorrentResolveFile;
use serde::{Deserialize, Serialize};

/// Metadata response returned by URL and torrent inspection resolvers.
#[derive(Debug, Serialize, Deserialize, Clone)]
#[serde(rename_all = "camelCase")]
pub struct ResolveResponse {
    /// Final effective URL after following all HTTP redirects.
    pub url: String,
    /// Inferred or server-provided filename (from URL path or Content-Disposition).
    pub filename: Option<String>,
    /// Total file length in bytes if known; `None` for streaming or chunked endpoints.
    pub total_size: Option<i64>,
    /// Inferred MIME type or extension string (e.g. "video/mp4", "application/pdf").
    pub file_type: Option<String>,
    /// Indicates whether the remote server advertises byte-range (`Accept-Ranges: bytes`) support.
    pub is_resumable: Option<bool>,
    /// List of internal files if the resolved URL is a BitTorrent magnet link or `.torrent` file.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub torrent_files: Option<Vec<TorrentResolveFile>>,
}
