//! TaskStatus, FileData, FileUri, GlobalStat
//!
//! ### Architectural Overview
//! - **What it does**: Defines core domain data models representing task states, file metadata, download URLs, and aggregate global download statistics.
//! - **How it does**: Serializes with `serde` camelCase field name conventions matching JSON-RPC expectations.
//! - **Where it comes from**: Generated by `DownloadManager`, `TaskSpawner`, and `TaskQueryManager`.
//! - **Where it leads to**: Returned in RPC responses to frontend dashboards and saved to disk in session files.

use super::torrent::TorrentInfo;
use serde::{Deserialize, Serialize};

/// Returns current system epoch timestamp in milliseconds.
pub fn default_created_at() -> u128 {
    std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .unwrap_or_default()
        .as_millis()
}

/// Comprehensive public status descriptor for a single download task.
#[derive(Debug, Serialize, Deserialize, Clone)]
#[serde(rename_all = "camelCase")]
pub struct TaskStatus {
    /// Unique Global Task Identifier (GID).
    pub gid: String,
    /// Current execution state ("active", "waiting", "paused", "complete", "error", "removed", "converting").
    pub status: String,
    /// Total expected size of download in bytes (as string for large file compatibility).
    pub total_length: String,
    /// Bytes downloaded and committed to disk so far.
    pub completed_length: String,
    /// Current instantaneous download speed in bytes per second.
    pub download_speed: String,
    /// Current upload speed in bytes per second (for active BitTorrent tasks).
    #[serde(skip_serializing_if = "Option::is_none")]
    pub upload_speed: Option<String>,
    /// Array of downloaded byte counts indexed per active worker thread.
    #[serde(default)]
    pub worker_progress: Vec<u64>,
    /// Inferred or reported MIME file type (e.g. "video/mp4", "application/pdf", "torrent").
    #[serde(skip_serializing_if = "Option::is_none")]
    pub file_type: Option<String>,
    /// Indicates whether the remote server supports HTTP byte-range resume.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub is_resumable: Option<bool>,
    /// List of target file descriptors contained in this task.
    pub files: Vec<FileData>,
    /// Destination directory path where downloaded files are saved.
    pub dir: String,
    /// BitTorrent metadata snapshot if this task is a peer-to-peer download.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub bittorrent: Option<TorrentInfo>,
    /// Hex-encoded BTIH InfoHash string if this is a BitTorrent download.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub info_hash: Option<String>,
    /// Number of connected BitTorrent seeders/peers.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub num_seeders: Option<u32>,
    /// Primary download source URL.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub url: Option<String>,
}

/// File metadata entry containing absolute disk path and source URIs.
#[derive(Debug, Serialize, Deserialize, Clone)]
pub struct FileData {
    /// Full absolute path to destination file on disk.
    pub path: String,
    /// List of mirror URIs available for downloading this file.
    pub uris: Vec<FileUri>,
}

/// Individual source URI entry.
#[derive(Debug, Serialize, Deserialize, Clone)]
pub struct FileUri {
    /// Remote source URL (HTTP, HTTPS, FTP, SFTP, Magnet).
    pub uri: String,
}

/// Aggregate system-wide bandwidth and task counter statistics.
#[derive(Debug, Serialize, Deserialize, Clone)]
#[serde(rename_all = "camelCase")]
pub struct GlobalStat {
    /// Combined real-time download bandwidth across all active tasks (bytes/sec).
    pub download_speed: String,
    /// Combined real-time upload bandwidth across all active torrents (bytes/sec).
    pub upload_speed: String,
    /// Count of currently downloading / converting tasks.
    pub num_active: String,
    /// Count of tasks in queue or paused state.
    pub num_waiting: String,
    /// Count of completed, failed, or stopped tasks in current memory.
    pub num_stopped: String,
    /// Historical count of stopped tasks.
    pub num_stopped_total: String,
}
