//! TorrentInfo, TorrentInfoInner, TorrentResolveFile
//!
//! ### Architectural Overview
//! - **What it does**: Defines data models representing BitTorrent metadata, tracker announce lists, multi-file hierarchies, and pre-download resolution files.
//! - **How it does**: Implements `serde::Serialize` and `serde::Deserialize` with camelCase renaming to provide standard torrent metadata snapshots.
//! - **Where it comes from**: Generated by `torrent::TorrentStatsTracker` and `resolver::TorrentResolver`.
//! - **Where it leads to**: Populates the `bittorrent` field on `TaskStatus` and `torrentFiles` array in `ResolveResponse`.

use serde::{Deserialize, Serialize};

/// High-level BitTorrent metadata snapshot attached to `TaskStatus`.
#[derive(Debug, Serialize, Deserialize, Clone)]
#[serde(rename_all = "camelCase")]
pub struct TorrentInfo {
    /// Tiered list of tracker announce URLs.
    pub announce_list: Vec<Vec<String>>,
    /// Optional creator comment.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub comment: Option<String>,
    /// Creation timestamp if specified in torrent dictionary.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub creation_date: Option<u64>,
    /// Torrent mode ("single" for single file, "multi" for multi-file torrents).
    pub mode: String,
    /// Inner torrent metadata dictionary.
    pub info: TorrentInfoInner,
}

/// Inner metadata dictionary containing the primary torrent name.
#[derive(Debug, Serialize, Deserialize, Clone)]
pub struct TorrentInfoInner {
    /// Top-level display name of the torrent payload or folder.
    pub name: String,
}

/// Individual file descriptor returned when resolving a `.torrent` file or magnet link.
#[derive(Debug, Serialize, Deserialize, Clone)]
pub struct TorrentResolveFile {
    /// 0-based file index within the torrent info structure.
    pub index: usize,
    /// Relative path of the file within the torrent directory hierarchy.
    pub path: String,
    /// File size in bytes.
    pub length: u64,
}
